kind: Service
apiVersion: v1
metadata:
  name: vote
  namespace: voting-app
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort

